language: php
php:
  - 7.2
  - 7.1
  - 7.0

addons:
  sonarcloud:
    organization: "miraheze"

script:
  # Check php script syntax
  - bash .travis.phplint.sh
  - sonar-scanner

notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    recipients:
      - southparkfan@miraheze.org
    on_success: change
    on_failure: always
